workflows:
  skillcraft_android_apk:
    name: SkillCraft Android APK
    instance_type: mac_mini_m2

    environment:
      node: 22
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app (Vite)
        script: |
          npm run build

      - name: Verify dist folder exists
        script: |
          ls -la
          test -f dist/index.html

      - name: Install Capacitor CLI + Android
        script: |
          npm i -D @capacitor/cli @capacitor/android

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Make gradlew executable (fix code 126)
        script: |
          chmod +x android/gradlew

      - name: Build Android APK (Debug)
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - android/build/reports/**/*