workflows:
  android-capacitor-workflow:
    name: Android Capacitor Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      node: latest
      groups:
        - google_play # Optional: if you have secret variables
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Capacitor Sync
        script: |
          # This links the Android project with your node_modules
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - appmanagement.ht@gmail.com # From your screen